version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:test
    networks:
      red:
        ipv4_address: 192.168.1.10
    ports:
      - "8080"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:test
    networks:
      black:
        ipv4_address: 192.168.2.10
    ports:
    - "8080"
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy:test
    networks:
      red: 
          ipv4_address: 192.168.1.150
      black:
          ipv4_address: 192.168.2.150
    ports:
      - "8080"

networks:
  red:
    ipam: 
      driver: default
      config: 
        - subnet: 192.168.1.0/24
  black:
    ipam: 
      driver: default
      config: 
        - subnet: 192.168.2.0/24
  